Homework1
made-ml-in-prod-2021/khubbatulinmark pull request #2
Opened 2021-05-09 20:45 UTC by KhubbatulinMark

Что сделано:
2) Назовите ветку homework1 (1 балл)  + 1  === СУММА: 1

-1) положите код в папку ml_project (0 баллов)  + 0  ===  СУММА: 1

0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла)  + 2  ===  СУММА: 3 (Ну вот же описание) и README)

1.) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 балла) + 2  === СУММА: 5
- Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
- Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) (1 балл) + 1  ===  СУММА: 6 (Скрипт описан в README) 

2.) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) + 2 === СУММА: 8

3.) использованы логгеры (2 балла)  + 2 === СУММА: 10

4.) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов)  +2 === СУММА: 12  (Мне кажется маловато тестов - если подскажиет что ещё добавить добавлю\исправлю)

5.) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов)  +2 === СУММА: 14 (Мне кажется маловато тестов - если подскажиет что ещё добавить добавлю\исправлю)

6.) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) +3 === СУММА: 17 

7.) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла)  +3 === СУММА: 20

8.)Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла)  +0 === СУММА: 20
Вот это не сделал - попробую добавить (если кнч можно)

9.)Обучите модель, запишите в readme как это предлагается (3 балла) +3 === СУММА: 23

10.) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла) +3 === СУММА: 26

11,)  Используется hydra (https://hydra.cc/docs/intro/) (3 балла - доп баллы) +3 === СУММА: 29

12.) Настроен CI(прогон тестов, линтера) на основе github actions (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) +3 === СУММА: 32

13.) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы) +1 === СУММА: 33

Если можно я добавлю трансформер и немного тестов
СУММА 33

2021-05-10 20:55 UTC, ol-ga-00 commented
@KhubbatulinMark! Да, у вас ещё есть время написать трансформер и дописать тесты (как минимум для predict и для трансформера, который вы напишете)

2021-05-10 21:00 UTC, ol-ga-00 commented
В отношении тестов рекомендую изучить статью https://habr.com/ru/post/448786/
Обратить внимание следует на "Спецификация областей(Scope) Fixture"

2021-05-10 21:11 UTC, ol-ga-00 commented
@Mikhail-M, важно ли, чтобы код первой домашки был в папке ml_project? Или его можно положить в папку с другим названием?

2021-05-12 18:46 UTC, Mikhail-M commented
> @Mikhail-M, важно ли, чтобы код первой домашки был в папке ml_project? Или его можно положить в папку с другим названием?

можно с другим, главное, чтобы рядом была возможность создать еще папку для другой домашки

2021-05-13 01:43 UTC, balan reviewed
Привет! Посмотрел код, слегка придрался к импортам (мне про них тоже подсказали)
В остальном всё вроде хорошо)

2021-05-13 01:43 UTC, balan commented on heart_disease/src/data/make_dataset.py
> +from src.entities import SplittingParams
Здесь можно использовать relative import
```suggestion
from ..entities import SplittingParams
```

2021-05-13 01:43 UTC, balan commented on heart_disease/src/features/build_features.py
> +from src.entities.feature_params import FeatureParams, TransformerConfig
Тоже relative import
```suggestion
from ..entities.feature_params import FeatureParams, TransformerConfig
```

2021-05-13 01:43 UTC, balan commented on heart_disease/src/make_report.py
> +from src.data import read_data
И во всех остальных случаях в файлах из src можно использовать relative import

2021-05-15 10:55 UTC, ol-ga-00 requested changes
Кроме написанных комментариев, вопросов больше нет!
Скажите, пожалуйста, к какому сроку вы планируете написать трансвормер и дописать тесты?

2021-05-15 10:55 UTC, ol-ga-00 commented on heart_disease/tests/train_data_sample.csv
> +age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
Я правильно понимаю, что этот файл нигде не используется?

2021-05-15 10:55 UTC, ol-ga-00 commented on heart_disease/tests/models/test_train_model.py
> +    data = read_data(dataset_path)
Не хотите read_data(dataset_path) вынести в фикстуру? Она много где используется!

2021-05-15 10:55 UTC, ol-ga-00 commented on heart_disease/tests/models/test_train_model.py
> +    assert model.predict(features).shape[0] == target.shape[0]
Полагаю, что этот assert бессмысленный!
Функция predict у RandomForestClassifier и у LogisticRegression всегда вернёт элемент, первая размерность которого будет совпадать с первой размерностью features
А размерности features и target совпадают, иначе бы функция train_model упала на моменте fit

2021-05-15 11:28 UTC, KhubbatulinMark commented
> Кроме написанных комментариев, вопросов больше нет!
> Скажите, пожалуйста, к какому сроку вы планируете написать трансвормер и дописать тесты?



> Кроме написанных комментариев, вопросов больше нет!
> Скажите, пожалуйста, к какому сроку вы планируете написать трансвормер и дописать тесты?

Здравствуйте, сегодня вечером буду исправлять недочёты. Завтра будет трансформер, тесты к нему и исправления

2021-05-16 16:32 UTC, KhubbatulinMark commented on heart_disease/tests/models/test_train_model.py
> +    data = read_data(dataset_path)
Везде теперь фикстура dataset

2021-05-16 16:32 UTC, KhubbatulinMark commented on heart_disease/tests/train_data_sample.csv
> +age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
убрал

2021-05-16 16:33 UTC, KhubbatulinMark commented on heart_disease/src/make_report.py
> +from src.data import read_data
изменил

> Кроме написанных комментариев, вопросов больше нет!
> Скажите, пожалуйста, к какому сроку вы планируете написать трансвормер и дописать тесты?

Добавил трансформер OutlierRemover. К нему дописал тест

2021-05-16 20:09 UTC, ol-ga-00 requested changes

2021-05-16 20:09 UTC, ol-ga-00 commented on heart_disease/tests/conftest.py
> +@pytest.fixture()
Предлагаю добавить scope как в эту фикстуру, так и в другие фикстуры

2021-05-16 20:42 UTC, KhubbatulinMark commented on heart_disease/tests/conftest.py
> +@pytest.fixture()
Добавил scope

2021-05-19 22:00 UTC, balan approved these changes
Всё здорово!

2021-05-20 20:36 UTC, ol-ga-00 approved these changes
Ставлю 38 баллов

2021-05-22 19:02 UTC, ol-ga-00 commented
@KhubbatulinMark, прошу смёрджить pr

2021-05-23 15:07 UTC, merged